datosgenerales = 
              {
                  Lider:
                    [ÁlvarezLópezAna,
                    ET1,
                    0],
                  Participante1:
                    [FreireSuárezEva,
                    ET1,
                    0],
                  Participante2:
                    [CortiñasPérezManuel,
                    ET1,
                    0],
                  Participante3:
                    [ElGhaliElGhaliHiba,
                     ET1,
                     0]
              }
