var accion_def_tests =  [
    ['accion', 'id_accion', 'input', 1, 'Validar min_size de id_accion en  ADD', 'min_size', 'ADD', 'id_accion_min_size_KO', 'El campo id_accion debe tener al menos 1 caracter'],
    ['accion', 'id_accion', 'input', 2, 'Validar max_size de id_accion en  ADD', 'max_size', 'ADD', 'id_accion_max_size_KO', 'El campo id_accion debe tener como máximo 11 caracteres'],
    ['accion', 'id_accion', 'input', 3, 'Validar format de id_accion en  ADD', 'format', 'ADD', 'id_accion_format_KO', 'El campo id_accion debe ser un número entero'],
    ['accion', 'id_accion', 'input', 4, 'Validar id_accion correcto en ADD', 'valid', 'ADD', 'true', 'id_accion correcto'],
    ['accion', 'id_accion', 'input', 5, 'Validar min_size de id_accion en  EDIT', 'min_size', 'EDIT', 'id_accion_min_size_KO', 'El campo id_accion debe tener al menos 1 caracter'],
    ['accion', 'id_accion', 'input', 6, 'Validar max_size de id_accion en  EDIT', 'max_size', 'EDIT', 'id_accion_max_size_KO', 'El campo id_accion debe tener como máximo 11 caracteres'],
    ['accion', 'id_accion', 'input', 7, 'Validar format de id_accion en  EDIT', 'format', 'EDIT', 'id_accion_format_KO', 'El campo id_accion debe ser un número entero'],
    ['accion', 'id_accion', 'input', 8, 'Validar id_accion correcto en EDIT', 'valid', 'EDIT', 'true', 'id_accion correcto'],
    ['accion', 'id_accion', 'input', 9, 'Validar max_size de id_accion en  SEARCH', 'max_size', 'SEARCH', 'id_accion_max_size_KO', 'El campo id_accion tiene como máximo 11 caracteres'],
    ['accion', 'id_accion', 'input', 10, 'Validar format de id_accion en  SEARCH', 'format', 'SEARCH', 'id_accion_format_KO', 'El campo id_accion debe ser un número entero'],
    ['accion', 'id_accion', 'input', 11, 'Validar id_accion correcto en SEARCH', 'valid', 'SEARCH', 'true', 'id_accion correcto'],
    ['accion', 'nombre_accion', 'input', 12, 'Validar min_size de nombre_accion en  ADD', 'min_size', 'ADD', 'nombre_accion_min_size_KO', 'El campo nombre_accion debe tener al menos 5 caracteres'],
    ['accion', 'nombre_accion', 'input', 13, 'Validar max_size de nombre_accion en  ADD', 'max_size', 'ADD', 'nombre_accion_max_size_KO', 'El campo nombre_accion debe tener como máximo 48 caracteres'],
    ['accion', 'nombre_accion', 'input', 14, 'Validar format de nombre_accion en  ADD', 'format', 'ADD', 'nombre_accion_format_KO', 'El campo nombre_accion debe ser alfabético incluyendo ñ'],
    ['accion', 'nombre_accion', 'input', 15, 'Validar nombre_accion correcto en ADD', 'valid', 'ADD', 'true', 'nombre_accion correcto'],
    ['accion', 'nombre_accion', 'input', 16, 'Validar min_size de nombre_accion en  EDIT', 'min_size', 'EDIT', 'nombre_accion_min_size_KO', 'El campo nombre_accion debe tener al menos 5 caracteres'],
    ['accion', 'nombre_accion', 'input', 17, 'Validar max_size de nombre_accion en  EDIT', 'max_size', 'EDIT', 'nombre_accion_max_size_KO', 'El campo nombre_accion debe tener como máximo 48 caracteres'],
    ['accion', 'nombre_accion', 'input', 18, 'Validar format de nombre_accion en  EDIT', 'format', 'EDIT', 'nombre_accion_format_KO', 'El campo nombre_accion debe ser alfabético incluyendo ñ'],
    ['accion', 'nombre_accion', 'input', 19, 'Validar nombre_accion correcto en EDIT', 'valid', 'EDIT', 'true', 'nombre_accion correcto'],
    ['accion', 'nombre_accion', 'input', 20, 'Validar max_size de nombre_accion en  SEARCH', 'max_size', 'SEARCH', 'nombre_accion_max_size_KO', 'El campo nombre_accion tiene como máximo 48 caracteres'],
    ['accion', 'nombre_accion', 'input', 21, 'Validar format de nombre_accion en  SEARCH', 'format', 'SEARCH', 'nombre_accion_format_KO', 'El campo nombre_accion debe ser alfabético incluyendo ñ'],
    ['accion', 'nombre_accion', 'input', 22, 'Validar nombre_accion correcto en SEARCH', 'valid', 'SEARCH', 'true', 'nombre_accion correcto'],
    ['accion', 'descrip_accion', 'textarea', 23, 'Validar min_size de descrip_accion en  ADD', 'min_size', 'ADD', 'descrip_accion_min_size_KO', 'El campo descrip_accion debe tener al menos 5 caracteres'],
    ['accion', 'descrip_accion', 'textarea', 24, 'Validar max_size de descrip_accion en  ADD', 'max_size', 'ADD', 'descrip_accion_max_size_KO', 'El campo descrip_accion debe tener como máximo 200 caracteres'],
    ['accion', 'descrip_accion', 'textarea', 25, 'Validar format de descrip_accion en  ADD', 'format', 'ADD', 'descrip_accion_format_KO', 'El campo descrip_accion debe ser alfabético incluyendo ñ, acentos y signos de puntuación'],
    ['accion', 'descrip_accion', 'textarea', 26, 'Validar descrip_accion correcto en ADD', 'valid', 'ADD', 'true', 'descrip_accion correcto'],
    ['accion', 'descrip_accion', 'textarea', 27, 'Validar min_size de descrip_accion en  EDIT', 'min_size', 'EDIT', 'descrip_accion_min_size_KO', 'El campo descrip_accion debe tener al menos 5 caracteres'],
    ['accion', 'descrip_accion', 'textarea', 28, 'Validar max_size de descrip_accion en  EDIT', 'max_size', 'EDIT', 'descrip_accion_max_size_KO', 'El campo descrip_accion debe tener como máximo 200 caracteres'],
    ['accion', 'descrip_accion', 'textarea', 29, 'Validar format de descrip_accion en  EDIT', 'format', 'EDIT', 'descrip_accion_format_KO', 'El campo descrip_accion debe ser alfabético incluyendo ñ, acentos y signos de puntuación'],
    ['accion', 'descrip_accion', 'textarea', 30, 'Validar descrip_accion correcto en EDIT', 'valid', 'EDIT', 'true', 'descrip_accion correcto'],
    ['accion', 'descrip_accion', 'textarea', 31, 'Validar max_size de descrip_accion en  SEARCH', 'max_size', 'SEARCH', 'descrip_accion_max_size_KO', 'El campo descrip_accion tiene como máximo 200 caracteres'],
    ['accion', 'descrip_accion', 'textarea', 32, 'Validar format de descrip_accion en  SEARCH', 'format', 'SEARCH', 'descrip_accion_format_KO', 'El campo descrip_accion debe ser alfabético incluyendo ñ, acentos y signos de puntuación'],
    ['accion', 'descrip_accion', 'textarea', 33, 'Validar descrip_accion correcto en SEARCH', 'valid', 'SEARCH', 'true', 'descrip_accion correcto']
];

var accion_pruebas = [
    ['accion', 'id_accion', 1, 1, 'ADD', {'id_accion': ''}, 'id_accion_min_size_KO'],
    ['accion', 'id_accion', 2, 2, 'ADD', {'id_accion': '123456789012'}, 'id_accion_max_size_KO'],
    ['accion', 'id_accion', 3, 3, 'ADD', {'id_accion': 'abc'}, 'id_accion_format_KO'],
    ['accion', 'id_accion', 4, 4, 'ADD', {'id_accion': '123'}, 'true'],
    ['accion', 'id_accion', 5, 5, 'EDIT', {'id_accion': ''}, 'id_accion_min_size_KO'],
    ['accion', 'id_accion', 6, 6, 'EDIT', {'id_accion': '123456789012'}, 'id_accion_max_size_KO'],
    ['accion', 'id_accion', 7, 7, 'EDIT', {'id_accion': 'abc'}, 'id_accion_format_KO'],
    ['accion', 'id_accion', 8, 8, 'EDIT', {'id_accion': '123'}, 'true'],
    ['accion', 'id_accion', 9, 9, 'SEARCH', {'id_accion': '123456789012'}, 'id_accion_max_size_KO'],
    ['accion', 'id_accion', 10, 10, 'SEARCH', {'id_accion': 'abc'}, 'id_accion_format_KO'],
    ['accion', 'id_accion', 11, 11, 'SEARCH', {'id_accion': '123'}, 'true'],
    ['accion', 'nombre_accion', 12, 12, 'ADD', {'nombre_accion': 'abc'}, 'nombre_accion_min_size_KO'],
    ['accion', 'nombre_accion', 13, 13, 'ADD', {'nombre_accion': 'a'.repeat(49)}, 'nombre_accion_max_size_KO'],
    ['accion', 'nombre_accion', 14, 14, 'ADD', {'nombre_accion': '1234'}, 'nombre_accion_format_KO'],
    ['accion', 'nombre_accion', 15, 15, 'ADD', {'nombre_accion': 'AccionConÑ'}, 'true'],
    ['accion', 'nombre_accion', 16, 16, 'EDIT', {'nombre_accion': 'abc'}, 'nombre_accion_min_size_KO'],
    ['accion', 'nombre_accion', 17, 17, 'EDIT', {'nombre_accion': 'a'.repeat(49)}, 'nombre_accion_max_size_KO'],
    ['accion', 'nombre_accion', 18, 18, 'EDIT', {'nombre_accion': '1234'}, 'nombre_accion_format_KO'],
    ['accion', 'nombre_accion', 19, 19, 'EDIT', {'nombre_accion': 'AccionConÑ'}, 'true'],
    ['accion', 'nombre_accion', 20, 20, 'SEARCH', {'nombre_accion': 'a'.repeat(49)}, 'nombre_accion_max_size_KO'],
    ['accion', 'nombre_accion', 21, 21, 'SEARCH', {'nombre_accion': '1234'}, 'nombre_accion_format_KO'],
    ['accion', 'nombre_accion', 22, 22, 'SEARCH', {'nombre_accion': 'AccionConÑ'}, 'true'],
    ['accion', 'descrip_accion', 23, 23, 'ADD', {'descrip_accion': 'abc'}, 'descrip_accion_min_size_KO'],
    ['accion', 'descrip_accion', 24, 24, 'ADD', {'descrip_accion': 'a'.repeat(201)}, 'descrip_accion_max_size_KO'],
    ['accion', 'descrip_accion', 25, 25, 'ADD', {'descrip_accion': '@@@@@@@@@@@@@@@@@@@@@'}, 'descrip_accion_format_KO'],
    ['accion', 'descrip_accion', 26, 26, 'ADD', {'descrip_accion': 'Descripción válida con acentos y signos de puntuación y ñ.'}, 'true'],
    ['accion', 'descrip_accion', 27, 27, 'EDIT', {'descrip_accion': 'abc'}, 'descrip_accion_min_size_KO'],
    ['accion', 'descrip_accion', 28, 28, 'EDIT', {'descrip_accion': 'a'.repeat(201)}, 'descrip_accion_max_size_KO'],
    ['accion', 'descrip_accion', 29, 29, 'EDIT', {'descrip_accion': '@@@@@@@@@@@@@@@@@@@@@'}, 'descrip_accion_format_KO'],
    ['accion', 'descrip_accion', 30, 30, 'EDIT', {'descrip_accion': 'Descripción válida con acentos y signos de puntuación y ñ.'}, 'true'],
    ['accion', 'descrip_accion', 31, 31, 'SEARCH', {'descrip_accion': 'a'.repeat(201)}, 'descrip_accion_max_size_KO'],
    ['accion', 'descrip_accion', 32, 32, 'SEARCH', {'descrip_accion': '@@@@@@@@@@@@@@@@@@@@@'}, 'descrip_accion_format_KO'],
    ['accion', 'descrip_accion', 33, 33, 'SEARCH', {'descrip_accion': 'Descripción válida con acentos y signos de puntuación y ñ.'}, 'true']
];
