datosgenerales = 
              {
                  Lider:
                    ['AlvarezLopezAna',
                    'ET1',
                    5.5],
                  Participante1:
                    ['FreireSuarezEva',
                    'ET1',
                    6.25],
                  Participante2:
                    ['CortiñasPerezManuel',
                    'ET1',
                    4],
                  Participante3:
                    ['ElGhaliElGhaliHiba',
                     'ET1',
                     3]
              }
