datosgenerales = 
              {
                  Lider:
                    ['AlvarezLopezAna',
                    'ET1',
                    7],
                  Participante1:
                    ['FreireSuarezEva',
                    'ET1',
                    6.25],
                  Participante2:
                    ['CortiñasPerezManuel',
                    'ET1',
                    6.5],
                  Participante3:
                    ['ElGhaliElGhaliHiba',
                     'ET1',
                     3]
              }
