var persona_def_tests = [
    ['persona', 'dni', 'input', 1, 'Validar min_size de dni en ADD', 'min_size', 'ADD', 'dni_min_size_KO', 'El campo dni debe tener al menos 9 caracteres'],
    ['persona', 'dni', 'input', 2, 'Validar max_size de dni en ADD', 'max_size', 'ADD', 'dni_max_size_KO', 'El campo dni debe tener como maximo 9 caracteres'],
    ['persona', 'dni', 'input', 3, 'Validar format de dni en ADD', 'format', 'ADD', 'dni_format_KO', 'El campo dni debe tener un formato DNI valido'],
    ['persona', 'dni', 'input', 4, 'Validar dni correcto en ADD', 'valid', 'ADD', true, 'dni correcto'],
    ['persona', 'dni', 'input', 5, 'Validar min_size de dni en EDIT', 'min_size', 'EDIT', 'dni_min_size_KO', 'El campo dni debe tener al menos 9 caracteres'],
    ['persona', 'dni', 'input', 6, 'Validar max_size de dni en EDIT', 'max_size', 'EDIT', 'dni_max_size_KO', 'El campo dni debe tener como maximo 9 caracteres'],
    ['persona', 'dni', 'input', 7, 'Validar format de dni en EDIT', 'format', 'EDIT', 'dni_format_KO', 'El campo dni debe tener un formato DNI valido'],
    ['persona', 'dni', 'input', 8, 'Validar dni correcto en EDIT', 'valid', 'EDIT', true, 'dni correcto'],
    ['persona', 'dni', 'input', 9, 'Validar max_size de dni en SEARCH', 'max_size', 'SEARCH', 'dni_max_size_KO', 'El campo dni debe tener como maximo 9 caracteres'],
    ['persona', 'dni', 'input', 10, 'Validar format de dni en SEARCH', 'format', 'SEARCH', 'dni_format_KO', 'El campo dni debe tener un formato DNI valido'],
    ['persona', 'dni', 'input', 11, 'Validar dni correcto en SEARCH', 'valid', 'SEARCH', true, 'dni correcto'],
    ['persona', 'nombre_persona', 'input', 12, 'Validar min_size de nombre_persona en ADD', 'min_size', 'ADD', 'nombre_persona_min_size_KO', 'El campo nombre_persona debe tener al menos 2 caracteres'],
    ['persona', 'nombre_persona', 'input', 13, 'Validar max_size de nombre_persona en ADD', 'max_size', 'ADD', 'nombre_persona_max_size_KO', 'El campo nombre_persona debe tener como maximo 45 caracteres'],
    ['persona', 'nombre_persona', 'input', 14, 'Validar formato de nombre_persona en ADD', 'format', 'ADD', 'nombre_persona_format_KO', 'El campo nombre_persona debe ser alfabetico incluyendo n, acentos, puntos, guiones y espacios'],
    ['persona', 'nombre_persona', 'input', 15, 'Validar nombre_persona correcto en ADD', 'valid', 'ADD', true, 'nombre_persona correcto'],
    ['persona', 'nombre_persona', 'input', 16, 'Validar min_size de nombre_persona en EDIT', 'min_size', 'EDIT', 'nombre_persona_min_size_KO', 'El campo nombre_persona debe tener al menos 2 caracteres'],
    ['persona', 'nombre_persona', 'input', 17, 'Validar max_size de nombre_persona en EDIT', 'max_size', 'EDIT', 'nombre_persona_max_size_KO', 'El campo nombre_persona debe tener como maximo 45 caracteres'],
    ['persona', 'nombre_persona', 'input', 18, 'Validar format de nombre_persona en EDIT', 'format', 'EDIT', 'nombre_persona_format_KO', 'El campo nombre_persona debe ser alfabetico incluyendo n, acentos, puntos, guiones y espacios'],
    ['persona', 'nombre_persona', 'input', 19, 'Validar nombre_persona correcto en EDIT', 'valid', 'EDIT', true, 'nombre_persona correcto'],
    ['persona', 'nombre_persona', 'input', 20, 'Validar max_size de nombre_persona en SEARCH', 'max_size', 'SEARCH', 'nombre_persona_max_size_KO', 'El campo nombre_persona tiene como maximo 45 caracteres'],
    ['persona', 'nombre_persona', 'input', 21, 'Validar format de nombre_persona en SEARCH', 'format', 'SEARCH', 'nombre_persona_format_KO', 'El campo nombre_persona debe ser alfabetico incluyendo n, acentos, puntos, guiones y espacios'],
    ['persona', 'nombre_persona', 'input', 22, 'Validar nombre_persona correcto en SEARCH', 'valid', 'SEARCH', true, 'nombre_persona correcto'],
    ['persona', 'apellidos_persona', 'input', 23, 'Validar min_size de apellidos_persona en ADD', 'min_size', 'ADD', 'apellidos_persona_min_size_KO', 'El campo apellidos_persona debe tener al menos 3 caracteres'],
    ['persona', 'apellidos_persona', 'input', 24, 'Validar max_size de apellidos_persona en ADD', 'max_size', 'ADD', 'apellidos_persona_max_size_KO', 'El campo apellidos_persona debe tener como maximo 100 caracteres'],
    ['persona', 'apellidos_persona', 'input', 25, 'Validar format de apellidos_persona en ADD', 'format', 'ADD', 'apellidos_persona_format_KO', 'El campo apellidos_persona debe ser alfabetico incluyendo n, acentos, puntos, guiones y espacios'],
    ['persona', 'apellidos_persona', 'input', 26, 'Validar apellidos_persona correcto en ADD', 'valid', 'ADD', true, 'apellidos_persona correcto'],
    ['persona', 'apellidos_persona', 'input', 27, 'Validar min_size de apellidos_persona en EDIT', 'min_size', 'EDIT', 'apellidos_persona_min_size_KO', 'El campo apellidos_persona debe tener al menos 3 caracteres'],
    ['persona', 'apellidos_persona', 'input', 28, 'Validar max_size de apellidos_persona en EDIT', 'max_size', 'EDIT', 'apellidos_persona_max_size_KO', 'El campo apellidos_persona debe tener como maximo 100 caracteres'],
    ['persona', 'apellidos_persona', 'input', 29, 'Validar format de apellidos_persona en EDIT', 'format', 'EDIT', 'apellidos_persona_format_KO', 'El campo apellidos_persona debe ser alfabetico incluyendo n, acentos, puntos, guiones y espacios'],
    ['persona', 'apellidos_persona', 'input', 30, 'Validar apellidos_persona correcto en EDIT', 'valid', 'EDIT', true, 'apellidos_persona correcto'],
    ['persona', 'apellidos_persona', 'input', 31, 'Validar max_size de apellidos_persona en SEARCH', 'max_size', 'SEARCH', 'apellidos_persona_max_size_KO', 'El campo apellidos_persona tiene como maximo 100 caracteres'],
    ['persona', 'apellidos_persona', 'input', 32, 'Validar format de apellidos_persona en SEARCH', 'format', 'SEARCH', 'apellidos_persona_format_KO', 'El campo apellidos_persona debe ser alfabetico incluyendo n, acentos, puntos, guiones y espacios'],
    ['persona', 'apellidos_persona', 'input', 33, 'Validar apellidos_persona correcto en SEARCH', 'valid', 'SEARCH', true, 'apellidos_persona correcto'],
    ['persona', 'fechaNacimiento_persona', 'input', 34, 'Validar min_size de fechaNacimiento_persona en ADD', 'min_size', 'ADD', 'fechaNacimiento_persona_min_size_KO', 'El campo fechaNacimiento_persona debe tener al menos 10 caracteres'],
	['persona', 'fechaNacimiento_persona', 'input', 35, 'Validar max_size de fechaNacimiento_persona en ADD', 'max_size', 'ADD', 'fechaNacimiento_persona_max_size_KO', 'El campo fechaNacimiento_persona debe tener como maximo 10 caracteres'],
	['persona', 'fechaNacimiento_persona', 'input', 36, 'Validar format de fechaNacimiento_persona en ADD', 'format', 'ADD', 'fechaNacimiento_persona_format_KO', 'El campo fechaNacimiento_persona debe tener formato dd/mm/aaaa'],
    ['persona', 'fechaNacimiento_persona', 'input', 37, 'Validar fechaNacimiento_persona correcta en ADD', 'valid', 'ADD', true, 'fechaNacimiento_persona correcta'],
	['persona', 'fechaNacimiento_persona', 'input', 38, 'Validar min_size de fechaNacimiento_persona en EDIT', 'min_size', 'EDIT', 'fechaNacimiento_persona_min_size_KO', 'El campo fechaNacimiento_persona debe tener al menos 10 caracteres'],
	['persona', 'fechaNacimiento_persona', 'input', 39, 'Validar max_size de fechaNacimiento_persona en EDIT', 'max_size', 'EDIT', 'fechaNacimiento_persona_max_size_KO', 'El campo fechaNacimiento_persona debe tener como maximo 10 caracteres'],
	['persona', 'fechaNacimiento_persona', 'input', 40, 'Validar format de fechaNacimiento_persona en EDIT', 'format', 'EDIT', 'fechaNacimiento_persona_format_KO', 'El campo fechaNacimiento_persona debe tener formato dd/mm/aaaa'],
    ['persona', 'fechaNacimiento_persona', 'input', 41, 'Validar fechaNacimiento_persona correcta en EDIT', 'valid', 'EDIT', true, 'fechaNacimiento_persona correcta'],
	['persona', 'fechaNacimiento_persona', 'input', 42, 'Validar max_size de fechaNacimiento_persona en SEARCH', 'max_size', 'SEARCH', 'fechaNacimiento_persona_max_size_KO', 'El campo fechaNacimiento_persona debe tener como maximo 10 caracteres'],
	['persona', 'fechaNacimiento_persona', 'input', 43, 'Validar format de fechaNacimiento_persona en SEARCH', 'format', 'SEARCH', 'fechaNacimiento_persona_format_KO', 'El campo fechaNacimiento_persona debe tener formato dd/mm/aaaa'],
    ['persona', 'fechaNacimiento_persona', 'input', 44, 'Validar fechaNacimiento_persona correcta en SEARCH', 'valid', 'SEARCH', true, 'fechaNacimiento_persona correcta'],
    ['persona', 'direccion_persona', 'input', 45, 'Validar min_size de direccion_persona en ADD', 'min_size', 'ADD', 'direccion_persona_min_size_KO', 'El campo direccion_persona debe tener al menos 10 caracteres'],
    ['persona', 'direccion_persona', 'input', 46, 'Validar max_size de direccion_persona en ADD', 'max_size', 'ADD', 'direccion_persona_max_size_KO', 'El campo direccion_persona debe tener como maximo 200 caracteres'],
    ['persona', 'direccion_persona', 'input', 47, 'Validar format de direccion_persona en ADD', 'format', 'ADD', 'direccion_persona_format_KO', 'El campo direccion_persona debe ser alfanumerico con n, acentos, puntos, guiones, punto y coma, espacios y /'],
    ['persona', 'direccion_persona', 'input', 48, 'Validar direccion_persona correcta en ADD', 'valid', 'ADD', true, 'direccion_persona correcta'],
    ['persona', 'direccion_persona', 'input', 49, 'Validar min_size de direccion_persona en EDIT', 'min_size', 'EDIT', 'direccion_persona_min_size_KO', 'El campo direccion_persona debe tener al menos 10 caracteres'],
    ['persona', 'direccion_persona', 'input', 50, 'Validar max_size de direccion_persona en EDIT', 'max_size', 'EDIT', 'direccion_persona_max_size_KO', 'El campo direccion_persona debe tener como maximo 200 caracteres'],
    ['persona', 'direccion_persona', 'input', 51, 'Validar format de direccion_persona en EDIT', 'format', 'EDIT', 'direccion_persona_format_KO', 'El campo direccion_persona debe ser alfanumerico con n, acentos, puntos, guiones, punto y coma, espacios y /'],
    ['persona', 'direccion_persona', 'input', 52, 'Validar direccion_persona correcta en EDIT', 'valid', 'EDIT', true, 'direccion_persona correcta'],
    ['persona', 'direccion_persona', 'input', 53, 'Validar max_size de direccion_persona en SEARCH', 'max_size', 'SEARCH', 'direccion_persona_max_size_KO', 'El campo direccion_persona tiene como maximo 200 caracteres'],
    ['persona', 'direccion_persona', 'input', 54, 'Validar format de direccion_persona en SEARCH', 'format', 'SEARCH', 'direccion_persona_format_KO', 'El campo direccion_persona debe ser alfanumerico con n, acentos, puntos, guiones, punto y coma, espacios y /'],
    ['persona', 'direccion_persona', 'input', 55, 'Validar direccion_persona correcta en SEARCH', 'valid', 'SEARCH', true, 'direccion_persona correcta'],
    ['persona', 'telefono_persona', 'input', 56, 'Validar min_size de telefono_persona en ADD', 'min_size', 'ADD', 'telefono_persona_min_size_KO', 'El campo telefono_persona debe tener al menos 9 caracteres'],
    ['persona', 'telefono_persona', 'input', 57, 'Validar max_size de telefono_persona en ADD', 'max_size', 'ADD', 'telefono_persona_max_size_KO', 'El campo telefono_persona debe tener como maximo 9 caracteres'],
    ['persona', 'telefono_persona', 'input', 58, 'Validar format de telefono_persona en ADD', 'format', 'ADD', 'telefono_persona_format_KO', 'El campo telefono_persona debe ser un telefono valido de Espana'],
    ['persona', 'telefono_persona', 'input', 59, 'Validar telefono_persona correcto en ADD', 'valid', 'ADD', true, 'telefono_persona correcto'],
    ['persona', 'telefono_persona', 'input', 60, 'Validar min_size de telefono_persona en EDIT', 'min_size', 'EDIT', 'telefono_persona_min_size_KO', 'El campo telefono_persona debe tener al menos 9 caracteres'],
    ['persona', 'telefono_persona', 'input', 61, 'Validar max_size de telefono_persona en EDIT', 'max_size', 'EDIT', 'telefono_persona_max_size_KO', 'El campo telefono_persona debe tener como maximo 9 caracteres'],
    ['persona', 'telefono_persona', 'input', 62, 'Validar format de telefono_persona en EDIT', 'format', 'EDIT', 'telefono_persona_format_KO', 'El campo telefono_persona debe ser un telefono valido de Espana'],
    ['persona', 'telefono_persona', 'input', 63, 'Validar telefono_persona correcto en EDIT', 'valid', 'EDIT', true, 'telefono_persona correcto'],
    ['persona', 'telefono_persona', 'input', 64, 'Validar max_size de telefono_persona en SEARCH', 'max_size', 'SEARCH', 'telefono_persona_max_size_KO', 'El campo telefono_persona debe tener como maximo 9 caracteres'],
    ['persona', 'telefono_persona', 'input', 65, 'Validar format de telefono_persona en SEARCH', 'format', 'SEARCH', 'telefono_persona_format_KO', 'El campo telefono_persona debe ser un telefono valido de Espana'],
    ['persona', 'telefono_persona', 'input', 66, 'Validar telefono_persona correcto en SEARCH', 'valid', 'SEARCH', true, 'telefono_persona correcto'],
    ['persona', 'email_persona', 'input', 67, 'Validar format de email_persona en ADD', 'format', 'ADD', 'email_persona_format_KO', 'El campo email_persona debe tener un formato de email valido'],
    ['persona', 'email_persona', 'input', 68, 'Validar email_persona correcto en ADD', 'valid', 'ADD', true, 'email_persona correcto'],
    ['persona', 'email_persona', 'input', 69, 'Validar format de email_persona en EDIT', 'format', 'EDIT', 'email_persona_format_KO', 'El campo email_persona debe tener un formato de email valido'],
    ['persona', 'email_persona', 'input', 70, 'Validar email_persona correcto en EDIT', 'valid', 'EDIT', true, 'email_persona correcto'],
    ['persona', 'email_persona', 'input', 71, 'Validar format de email_persona en SEARCH', 'format', 'SEARCH', 'email_persona_format_KO', 'El campo email_persona debe tener un formato de email valido'],
    ['persona', 'email_persona', 'input', 72, 'Validar email_persona correcto en SEARCH', 'valid', 'SEARCH', true, 'email_persona correcto'],
	['persona', 'nuevo_foto_persona', 'file', 73, 'Existe fichero en foto_persona ADD', 'exist_file', 'ADD', 'foto_persona_exist_file_KO', 'No existe foto. Debe subir una foto en jpg o jpeg'],
	['persona', 'nuevo_foto_persona', 'file', 74, 'Minimo nombre fichero foto ADD', 'min_name_file', 'ADD', 'foto_persona_min_name_file_KO', 'Nombre de foto incorrecto. Debe tener al menos 3 caracteres'],
	['persona', 'nuevo_foto_persona', 'file', 75, 'Maximo nombre fichero foto ADD', 'max_name_file', 'ADD', 'foto_persona_max_name_file_KO', 'Nombre de foto incorrecto. Debe tener como maximo 15 caracteres'],
	['persona', 'nuevo_foto_persona', 'file', 76, 'Formato nombre fichero foto ADD', 'format_name_file', 'ADD', 'foto_persona_format_name_file_KO', 'Nombre de foto incorrecto. Debe ser alfabetico y terminar en .jpg o .jpeg'],
    ['persona', 'nuevo_foto_persona', 'file', 77, 'Tamaño fichero foto ADD', 'max_size_file', 'ADD', 'foto_persona_max_size_file_KO', 'Tamaño de fichero excesivo. Debe ser menor de 2 MB'],
	['persona', 'nuevo_foto_persona', 'file', 78, 'Validar formato fichero foto ADD', 'format', 'ADD', 'foto_persona_format_KO', 'Debe ser un archivo jpg o jpeg'],
    ['persona', 'nuevo_foto_persona', 'file', 79, 'Validar foto_persona correcta en ADD', 'valid', 'ADD', true, 'foto_persona correcta'],
	['persona', 'nuevo_foto_persona', 'file', 80, 'Existe fichero en foto_persona EDIT', 'exist_file', 'EDIT', true, ''],
    ['persona', 'nuevo_foto_persona', 'file', 81, 'Minimo nombre fichero foto EDIT', 'min_name_file', 'EDIT', 'foto_persona_min_name_file_KO', 'Nombre de foto incorrecto. Debe tener al menos 3 caracteres'],
	['persona', 'nuevo_foto_persona', 'file', 82, 'Maximo nombre fichero foto EDIT', 'max_name_file', 'EDIT', 'foto_persona_max_name_file_KO', 'Nombre de foto incorrecto. Debe tener como maximo 15 caracteres'],
	['persona', 'nuevo_foto_persona', 'file', 83, 'Formato nombre fichero foto EDIT', 'format_name_file', 'EDIT', 'foto_persona_format_name_file_KO', 'Nombre de foto incorrecto. Debe ser alfabetico y terminar en .jpg o .jpeg'],
    ['persona', 'nuevo_foto_persona', 'file', 84, 'Tamaño fichero foto EDIT', 'max_size_file', 'EDIT', 'foto_persona_max_size_file_KO', 'Tamaño de fichero excesivo. Debe ser menor de 2 MB'],
    ['persona', 'nuevo_foto_persona', 'file', 85, 'Validar formato fichero foto EDIT', 'format', 'EDIT', 'foto_persona_format_KO', 'Debe ser un archivo jpg o jpeg'],
    ['persona', 'nuevo_foto_persona', 'file', 86, 'Validar foto_persona correcta en EDIT', 'valid', 'EDIT', true, 'foto_persona correcta'],
    ['persona', 'foto_persona', 'file', 87, 'Formato nombre fichero foto SEARCH', 'format_name_file', 'SEARCH', 'foto_persona_format_name_file_KO', 'Nombre de foto incorrecto. Debe ser alfabetico y terminar en .jpg o .jpeg'],
    ['persona', 'foto_persona', 'file', 88, 'Tamaño fichero foto SEARCH', 'max_size_file', 'SEARCH', 'foto_persona_max_name_file_KO', 'Tamaño de fichero excesivo. Debe ser menor de 2 MB'],
    ['persona', 'foto_persona', 'file', 89, 'Validar foto_persona correcta en SEARCH', 'valid', 'SEARCH', true, 'foto_persona correcta'],
];

var persona_pruebas = [
    ['persona', 'dni', 1, 1, 'ADD', {'dni': '1234567'}, 'dni_min_size_KO'],
    ['persona', 'dni', 2, 2, 'ADD', {'dni': '1234567890'}, 'dni_max_size_KO'],
    ['persona', 'dni', 3, 3, 'ADD', {'dni': '12345678A'}, 'dni_format_KO'],
    ['persona', 'dni', 4, 4, 'ADD', {'dni': '12345678Z'}, true],
    ['persona', 'dni', 5, 5, 'EDIT', {'dni': '1234567'}, 'dni_min_size_KO'],
    ['persona', 'dni', 6, 6, 'EDIT', {'dni': '1234567890'}, 'dni_max_size_KO'],
    ['persona', 'dni', 7, 7, 'EDIT', {'dni': '12345678A'}, 'dni_format_KO'],
    ['persona', 'dni', 8, 8, 'EDIT', {'dni': '12345678Z'}, true],
    ['persona', 'dni', 9, 9, 'SEARCH', {'dni': '1234567890'}, 'dni_max_size_KO'],
    ['persona', 'dni', 10, 10, 'SEARCH', {'dni': '12345678A'}, 'dni_format_KO'],
    ['persona', 'dni', 11, 11, 'SEARCH', {'dni': '12345678Z'}, true],
    ['persona', 'nombre_persona', 12, 12, 'ADD', {'nombre_persona': 'A'}, 'nombre_persona_min_size_KO'],
    ['persona', 'nombre_persona', 13, 13, 'ADD', {'nombre_persona': 'a'.repeat(46)}, 'nombre_persona_max_size_KO'],
    ['persona', 'nombre_persona', 14, 14, 'ADD', {'nombre_persona': 'Ana123'}, 'nombre_persona_format_KO'],
    ['persona', 'nombre_persona', 15, 15, 'ADD', {'nombre_persona': 'Maria Jose'}, true],
    ['persona', 'nombre_persona', 16, 16, 'EDIT', {'nombre_persona': 'A'}, 'nombre_persona_min_size_KO'],
    ['persona', 'nombre_persona', 17, 17, 'EDIT', {'nombre_persona': 'a'.repeat(46)}, 'nombre_persona_max_size_KO'],
    ['persona', 'nombre_persona', 18, 18, 'EDIT', {'nombre_persona': 'Ana123'}, 'nombre_persona_format_KO'],
    ['persona', 'nombre_persona', 19, 19, 'EDIT', {'nombre_persona': 'Maria Jose'}, true],
    ['persona', 'nombre_persona', 20, 20, 'SEARCH', {'nombre_persona': 'a'.repeat(46)}, 'nombre_persona_max_size_KO'],
    ['persona', 'nombre_persona', 21, 21, 'SEARCH', {'nombre_persona': 'Ana123'}, 'nombre_persona_format_KO'],
    ['persona', 'nombre_persona', 22, 22, 'SEARCH', {'nombre_persona': 'Maria Jose'}, true],
    ['persona', 'apellidos_persona', 23, 23, 'ADD', {'apellidos_persona': 'Lo'}, 'apellidos_persona_min_size_KO'],
    ['persona', 'apellidos_persona', 24, 24, 'ADD', {'apellidos_persona': 'a'.repeat(101)}, 'apellidos_persona_max_size_KO'],
    ['persona', 'apellidos_persona', 25, 25, 'ADD', {'apellidos_persona': 'Perez123'}, 'apellidos_persona_format_KO'],
    ['persona', 'apellidos_persona', 26, 26, 'ADD', {'apellidos_persona': 'Garcia-Lopez'}, true],
    ['persona', 'apellidos_persona', 27, 27, 'EDIT', {'apellidos_persona': 'Lo'}, 'apellidos_persona_min_size_KO'],
    ['persona', 'apellidos_persona', 28, 28, 'EDIT', {'apellidos_persona': 'a'.repeat(101)}, 'apellidos_persona_max_size_KO'],
    ['persona', 'apellidos_persona', 29, 29, 'EDIT', {'apellidos_persona': 'Perez123'}, 'apellidos_persona_format_KO'],
    ['persona', 'apellidos_persona', 30, 30, 'EDIT', {'apellidos_persona': 'Garcia-Lopez'}, true],
    ['persona', 'apellidos_persona', 31, 31, 'SEARCH', {'apellidos_persona': 'a'.repeat(101)}, 'apellidos_persona_max_size_KO'],
    ['persona', 'apellidos_persona', 32, 32, 'SEARCH', {'apellidos_persona': 'Perez123'}, 'apellidos_persona_format_KO'],
    ['persona', 'apellidos_persona', 33, 33, 'SEARCH', {'apellidos_persona': 'Garcia-Lopez'}, true],
	['persona', 'fechaNacimiento_persona', 34, 34, 'ADD', {'fechaNacimiento_persona': '23'}, 'fechaNacimiento_persona_min_size_KO'],
	['persona', 'fechaNacimiento_persona', 35, 35, 'ADD', {'fechaNacimiento_persona': '23/09/2020/extra'}, 'fechaNacimiento_persona_max_size_KO'],
    ['persona', 'fechaNacimiento_persona', 36, 36, 'ADD', {'fechaNacimiento_persona': '2020-09-23'}, 'fechaNacimiento_persona_format_KO'],
    ['persona', 'fechaNacimiento_persona', 37, 37, 'ADD', {'fechaNacimiento_persona': '23/09/2020'}, true],
	['persona', 'fechaNacimiento_persona', 38, 38, 'EDIT', {'fechaNacimiento_persona': '23'}, 'fechaNacimiento_persona_min_size_KO'],
	['persona', 'fechaNacimiento_persona', 39, 39, 'EDIT', {'fechaNacimiento_persona': '23/09/2020/extra'}, 'fechaNacimiento_persona_max_size_KO'],
    ['persona', 'fechaNacimiento_persona', 40, 40, 'EDIT', {'fechaNacimiento_persona': '2020-09-23'}, 'fechaNacimiento_persona_format_KO'],
    ['persona', 'fechaNacimiento_persona', 41, 41, 'EDIT', {'fechaNacimiento_persona': '23/09/2020'}, true],
	['persona', 'fechaNacimiento_persona', 42, 42, 'SEARCH', {'fechaNacimiento_persona': '23/09/2020/extra'}, 'fechaNacimiento_persona_max_size_KO'],
    ['persona', 'fechaNacimiento_persona', 43, 43, 'SEARCH', {'fechaNacimiento_persona': '2020-09-23'}, 'fechaNacimiento_persona_format_KO'],
    ['persona', 'fechaNacimiento_persona', 44, 44, 'SEARCH', {'fechaNacimiento_persona': '23/09/2020'}, true],
    ['persona', 'direccion_persona', 45, 45, 'ADD', {'direccion_persona': 'Calle 1'}, 'direccion_persona_min_size_KO'],
    ['persona', 'direccion_persona', 46, 46, 'ADD', {'direccion_persona': 'a'.repeat(201)}, 'direccion_persona_max_size_KO'],
    ['persona', 'direccion_persona', 47, 47, 'ADD', {'direccion_persona': 'Calle @@@'}, 'direccion_persona_format_KO'],
    ['persona', 'direccion_persona', 48, 48, 'ADD', {'direccion_persona': 'Calle 10; 2/A'}, true],
    ['persona', 'direccion_persona', 49, 49, 'EDIT', {'direccion_persona': 'Calle 1'}, 'direccion_persona_min_size_KO'],
    ['persona', 'direccion_persona', 50, 50, 'EDIT', {'direccion_persona': 'a'.repeat(201)}, 'direccion_persona_max_size_KO'],
    ['persona', 'direccion_persona', 51, 51, 'EDIT', {'direccion_persona': 'Calle @@@'}, 'direccion_persona_format_KO'],
    ['persona', 'direccion_persona', 52, 52, 'EDIT', {'direccion_persona': 'Calle 10; 2/A'}, true],
    ['persona', 'direccion_persona', 53, 53, 'SEARCH', {'direccion_persona': 'a'.repeat(201)}, 'direccion_persona_max_size_KO'],
    ['persona', 'direccion_persona', 54, 54, 'SEARCH', {'direccion_persona': 'Calle @@@'}, 'direccion_persona_format_KO'],
    ['persona', 'direccion_persona', 55, 55, 'SEARCH', {'direccion_persona': 'Calle 10; 2/A'}, true],
	['persona', 'telefono_persona', 56, 56, 'ADD', {'telefono_persona': '1234567'}, 'telefono_persona_min_size_KO'],
	['persona', 'telefono_persona', 57, 57, 'ADD', {'telefono_persona': '1234567890'}, 'telefono_persona_max_size_KO'],
    ['persona', 'telefono_persona', 58, 58, 'ADD', {'telefono_persona': '12345678'}, 'telefono_persona_format_KO'],
    ['persona', 'telefono_persona', 59, 59, 'ADD', {'telefono_persona': '612345678'}, true],
	['persona', 'telefono_persona', 60, 60, 'EDIT', {'telefono_persona': '1234567'}, 'telefono_persona_min_size_KO'],
	['persona', 'telefono_persona', 61, 61, 'EDIT', {'telefono_persona': '1234567890'}, 'telefono_persona_max_size_KO'],
    ['persona', 'telefono_persona', 62, 62, 'EDIT', {'telefono_persona': '12345678'}, 'telefono_persona_format_KO'],
    ['persona', 'telefono_persona', 63, 63, 'EDIT', {'telefono_persona': '612345678'}, true],
	['persona', 'telefono_persona', 64, 64, 'SEARCH', {'telefono_persona': '1234567890'}, 'telefono_persona_max_size_KO'],
    ['persona', 'telefono_persona', 65, 65, 'SEARCH', {'telefono_persona': '12345678'}, 'telefono_persona_format_KO'],
    ['persona', 'telefono_persona', 66, 66, 'SEARCH', {'telefono_persona': '612345678'}, true],
    ['persona', 'email_persona', 67, 67, 'ADD', {'email_persona': 'correo'}, 'email_persona_format_KO'],
    ['persona', 'email_persona', 68, 68, 'ADD', {'email_persona': 'persona@example.com'}, true],
    ['persona', 'email_persona', 69, 69, 'EDIT', {'email_persona': 'correo'}, 'email_persona_format_KO'],
    ['persona', 'email_persona', 70, 70, 'EDIT', {'email_persona': 'persona@example.com'}, true],
    ['persona', 'email_persona', 71, 71, 'SEARCH', {'email_persona': 'correo'}, 'email_persona_format_KO'],
    ['persona', 'email_persona', 72, 72, 'SEARCH', {'email_persona': 'persona@example.com'}, true],
    ['persona', 'nuevo_foto_persona', 73, 73, 'ADD', {}, 'foto_persona_exist_file_KO'],
	['persona', 'nuevo_foto_persona', 74, 74, 'ADD',{nuevo_foto_persona:{format_name_file: 'fo.jpg', type_file: 'image/jpeg', max_size_file: 200000}}, 'foto_persona_min_name_file_KO'],
	['persona', 'nuevo_foto_persona', 75, 75, 'ADD', {nuevo_foto_persona: {format_name_file: 'foto123456789012345.jpg', type_file: 'image/jpeg', max_size_file: 200000}}, 'foto_persona_max_name_file_KO'],
    ['persona', 'nuevo_foto_persona', 76, 76, 'ADD', {nuevo_foto_persona: {format_name_file: 'foto123.jpg', type_file: 'image/jpeg', max_size_file: 200000}}, 'foto_persona_format_name_file_KO'],
    ['persona', 'nuevo_foto_persona', 77, 77, 'ADD', {nuevo_foto_persona: {format_name_file: 'foto.jpg', type_file: 'image/jpeg', max_size_file: 3000000}}, 'foto_persona_max_size_file_KO'],
	['persona', 'nuevo_foto_persona', 78, 78, 'ADD', {nuevo_foto_persona: {format_name_file: 'foto.jpg', type_file: 'image/png', max_size_file: 200000}}, 'foto_persona_format_KO'],
    ['persona', 'nuevo_foto_persona', 79, 79, 'ADD', {nuevo_foto_persona: {format_name_file: 'foto.jpg', type_file: 'image/jpeg', max_size_file: 200000}}, true],
    ['persona', 'nuevo_foto_persona', 80, 80, 'EDIT', {}, true],
	['persona', 'nuevo_foto_persona', 81, 81, 'EDIT', {nuevo_foto_persona: {format_name_file: 'fo.jpg', type_file: 'image/jpeg', max_size_file: 200000}}, 'foto_persona_min_name_file_KO'],
	['persona', 'nuevo_foto_persona', 82, 82, 'EDIT', {nuevo_foto_persona: {format_name_file: 'foto123456789012345.jpg', type_file: 'image/jpeg', max_size_file: 200000}}, 'foto_persona_max_name_file_KO'],
    ['persona', 'nuevo_foto_persona', 83, 83, 'EDIT', {nuevo_foto_persona: {format_name_file: 'foto123.jpg', type_file: 'image/jpeg', max_size_file: 200000}}, 'foto_persona_format_name_file_KO'],
    ['persona', 'nuevo_foto_persona', 84, 84, 'EDIT', {nuevo_foto_persona: {format_name_file: 'foto.jpg', type_file: 'image/jpeg', max_size_file: 3000000}}, 'foto_persona_max_size_file_KO'],
	['persona', 'nuevo_foto_persona', 85, 85, 'EDIT', {nuevo_foto_persona: {format_name_file: 'foto.jpg', type_file: 'image/png', max_size_file: 200000}}, 'foto_persona_format_KO'],
    ['persona', 'nuevo_foto_persona', 86, 86, 'EDIT', {nuevo_foto_persona: {format_name_file: 'foto.jpg', type_file: 'image/jpeg', max_size_file: 200000}}, true],
    ['persona', 'foto_persona', 87, 88, 'SEARCH', {foto_persona: 'foto123.jpg'}, 'foto_persona_format_name_file_KO'],
    ['persona', 'foto_persona', 88, 89, 'SEARCH', {foto_persona: 'f'.repeat(16) + '.jpg'}, 'foto_persona_max_name_file_KO'],
    ['persona', 'foto_persona', 89, 90, 'SEARCH', {foto_persona: 'foto.jpg'}, true],
];