var persona_def_tests = [
	['persona', 'dni', 'input', 1, 'Validar format de dni en ADD', 'format', 'ADD', 'dni_format_KO', 'El campo dni debe tener un formato DNI valido'],
	['persona', 'dni', 'input', 2, 'Validar dni correcto en ADD', 'valid', 'ADD', true, 'dni correcto'],
	['persona', 'dni', 'input', 3, 'Validar format de dni en EDIT', 'format', 'EDIT', 'dni_format_KO', 'El campo dni debe tener un formato DNI valido'],
	['persona', 'dni', 'input', 4, 'Validar dni correcto en EDIT', 'valid', 'EDIT', true, 'dni correcto'],
	['persona', 'dni', 'input', 5, 'Validar format de dni en SEARCH', 'format', 'SEARCH', 'dni_format_KO', 'El campo dni debe tener un formato DNI valido'],
	['persona', 'dni', 'input', 6, 'Validar dni correcto en SEARCH', 'valid', 'SEARCH', true, 'dni correcto'],
	['persona', 'nombre_persona', 'input', 7, 'Validar min_size de nombre_persona en ADD', 'min_size', 'ADD', 'nombre_persona_min_size_KO', 'El campo nombre_persona debe tener al menos 2 caracteres'],
	['persona', 'nombre_persona', 'input', 8, 'Validar max_size de nombre_persona en ADD', 'max_size', 'ADD', 'nombre_persona_max_size_KO', 'El campo nombre_persona debe tener como maximo 45 caracteres'],
	['persona', 'nombre_persona', 'input', 9, 'Validar formato de nombre_persona en ADD', 'format', 'ADD', 'nombre_persona_format_KO', 'El campo nombre_persona debe ser alfabetico incluyendo n, acentos, puntos, guiones y espacios'],
	['persona', 'nombre_persona', 'input', 10, 'Validar nombre_persona correcto en ADD', 'valid', 'ADD', true, 'nombre_persona correcto'],
	['persona', 'nombre_persona', 'input', 11, 'Validar min_size de nombre_persona en EDIT', 'min_size', 'EDIT', 'nombre_persona_min_size_KO', 'El campo nombre_persona debe tener al menos 2 caracteres'],
	['persona', 'nombre_persona', 'input', 12, 'Validar max_size de nombre_persona en EDIT', 'max_size', 'EDIT', 'nombre_persona_max_size_KO', 'El campo nombre_persona debe tener como maximo 45 caracteres'],
	['persona', 'nombre_persona', 'input', 13, 'Validar format de nombre_persona en EDIT', 'format', 'EDIT', 'nombre_persona_format_KO', 'El campo nombre_persona debe ser alfabetico incluyendo n, acentos, puntos, guiones y espacios'],
	['persona', 'nombre_persona', 'input', 14, 'Validar nombre_persona correcto en EDIT', 'valid', 'EDIT', true, 'nombre_persona correcto'],
	['persona', 'nombre_persona', 'input', 15, 'Validar max_size de nombre_persona en SEARCH', 'max_size', 'SEARCH', 'nombre_persona_max_size_KO', 'El campo nombre_persona tiene como maximo 45 caracteres'],
	['persona', 'nombre_persona', 'input', 16, 'Validar format de nombre_persona en SEARCH', 'format', 'SEARCH', 'nombre_persona_format_KO', 'El campo nombre_persona debe ser alfabetico incluyendo n, acentos, puntos, guiones y espacios'],
	['persona', 'nombre_persona', 'input', 17, 'Validar nombre_persona correcto en SEARCH', 'valid', 'SEARCH', true, 'nombre_persona correcto'],
	['persona', 'apellidos_persona', 'input', 18, 'Validar min_size de apellidos_persona en ADD', 'min_size', 'ADD', 'apellidos_persona_min_size_KO', 'El campo apellidos_persona debe tener al menos 3 caracteres'],
	['persona', 'apellidos_persona', 'input', 19, 'Validar max_size de apellidos_persona en ADD', 'max_size', 'ADD', 'apellidos_persona_max_size_KO', 'El campo apellidos_persona debe tener como maximo 100 caracteres'],
	['persona', 'apellidos_persona', 'input', 20, 'Validar format de apellidos_persona en ADD', 'format', 'ADD', 'apellidos_persona_format_KO', 'El campo apellidos_persona debe ser alfabetico incluyendo n, acentos, puntos, guiones y espacios'],
	['persona', 'apellidos_persona', 'input', 21, 'Validar apellidos_persona correcto en ADD', 'valid', 'ADD', true, 'apellidos_persona correcto'],
	['persona', 'apellidos_persona', 'input', 22, 'Validar min_size de apellidos_persona en EDIT', 'min_size', 'EDIT', 'apellidos_persona_min_size_KO', 'El campo apellidos_persona debe tener al menos 3 caracteres'],
	['persona', 'apellidos_persona', 'input', 23, 'Validar max_size de apellidos_persona en EDIT', 'max_size', 'EDIT', 'apellidos_persona_max_size_KO', 'El campo apellidos_persona debe tener como maximo 100 caracteres'],
	['persona', 'apellidos_persona', 'input', 24, 'Validar format de apellidos_persona en EDIT', 'format', 'EDIT', 'apellidos_persona_format_KO', 'El campo apellidos_persona debe ser alfabetico incluyendo n, acentos, puntos, guiones y espacios'],
	['persona', 'apellidos_persona', 'input', 25, 'Validar apellidos_persona correcto en EDIT', 'valid', 'EDIT', true, 'apellidos_persona correcto'],
	['persona', 'apellidos_persona', 'input', 26, 'Validar max_size de apellidos_persona en SEARCH', 'max_size', 'SEARCH', 'apellidos_persona_max_size_KO', 'El campo apellidos_persona tiene como maximo 100 caracteres'],
	['persona', 'apellidos_persona', 'input', 27, 'Validar format de apellidos_persona en SEARCH', 'format', 'SEARCH', 'apellidos_persona_format_KO', 'El campo apellidos_persona debe ser alfabetico incluyendo n, acentos, puntos, guiones y espacios'],
	['persona', 'apellidos_persona', 'input', 28, 'Validar apellidos_persona correcto en SEARCH', 'valid', 'SEARCH', true, 'apellidos_persona correcto'],
	['persona', 'fechaNacimiento_persona', 'input', 29, 'Validar format de fechaNacimiento_persona en ADD', 'format', 'ADD', 'fechaNacimiento_persona_format_KO', 'El campo fechaNacimiento_persona debe tener formato dd/mm/aaaa'],
	['persona', 'fechaNacimiento_persona', 'input', 30, 'Validar fechaNacimiento_persona correcta en ADD', 'valid', 'ADD', true, 'fechaNacimiento_persona correcta'],
	['persona', 'fechaNacimiento_persona', 'input', 31, 'Validar format de fechaNacimiento_persona en EDIT', 'format', 'EDIT', 'fechaNacimiento_persona_format_KO', 'El campo fechaNacimiento_persona debe tener formato dd/mm/aaaa'],
	['persona', 'fechaNacimiento_persona', 'input', 32, 'Validar fechaNacimiento_persona correcta en EDIT', 'valid', 'EDIT', true, 'fechaNacimiento_persona correcta'],
	['persona', 'fechaNacimiento_persona', 'input', 33, 'Validar format de fechaNacimiento_persona en SEARCH', 'format', 'SEARCH', 'fechaNacimiento_persona_format_KO', 'El campo fechaNacimiento_persona debe tener formato dd/mm/aaaa'],
	['persona', 'fechaNacimiento_persona', 'input', 34, 'Validar fechaNacimiento_persona correcta en SEARCH', 'valid', 'SEARCH', true, 'fechaNacimiento_persona correcta'],
	['persona', 'direccion_persona', 'input', 35, 'Validar min_size de direccion_persona en ADD', 'min_size', 'ADD', 'direccion_persona_min_size_KO', 'El campo direccion_persona debe tener al menos 10 caracteres'],
	['persona', 'direccion_persona', 'input', 36, 'Validar max_size de direccion_persona en ADD', 'max_size', 'ADD', 'direccion_persona_max_size_KO', 'El campo direccion_persona debe tener como maximo 200 caracteres'],
	['persona', 'direccion_persona', 'input', 37, 'Validar format de direccion_persona en ADD', 'format', 'ADD', 'direccion_persona_format_KO', 'El campo direccion_persona debe ser alfanumerico con n, acentos, puntos, guiones, punto y coma, espacios y /'],
	['persona', 'direccion_persona', 'input', 38, 'Validar direccion_persona correcta en ADD', 'valid', 'ADD', true, 'direccion_persona correcta'],
	['persona', 'direccion_persona', 'input', 39, 'Validar min_size de direccion_persona en EDIT', 'min_size', 'EDIT', 'direccion_persona_min_size_KO', 'El campo direccion_persona debe tener al menos 10 caracteres'],
	['persona', 'direccion_persona', 'input', 40, 'Validar max_size de direccion_persona en EDIT', 'max_size', 'EDIT', 'direccion_persona_max_size_KO', 'El campo direccion_persona debe tener como maximo 200 caracteres'],
	['persona', 'direccion_persona', 'input', 41, 'Validar format de direccion_persona en EDIT', 'format', 'EDIT', 'direccion_persona_format_KO', 'El campo direccion_persona debe ser alfanumerico con n, acentos, puntos, guiones, punto y coma, espacios y /'],
	['persona', 'direccion_persona', 'input', 42, 'Validar direccion_persona correcta en EDIT', 'valid', 'EDIT', true, 'direccion_persona correcta'],
	['persona', 'direccion_persona', 'input', 43, 'Validar max_size de direccion_persona en SEARCH', 'max_size', 'SEARCH', 'direccion_persona_max_size_KO', 'El campo direccion_persona tiene como maximo 200 caracteres'],
	['persona', 'direccion_persona', 'input', 44, 'Validar format de direccion_persona en SEARCH', 'format', 'SEARCH', 'direccion_persona_format_KO', 'El campo direccion_persona debe ser alfanumerico con n, acentos, puntos, guiones, punto y coma, espacios y /'],
	['persona', 'direccion_persona', 'input', 45, 'Validar direccion_persona correcta en SEARCH', 'valid', 'SEARCH', true, 'direccion_persona correcta'],
	['persona', 'telefono_persona', 'input', 46, 'Validar format de telefono_persona en ADD', 'format', 'ADD', 'telefono_persona_format_KO', 'El campo telefono_persona debe ser un telefono valido de Espana'],
	['persona', 'telefono_persona', 'input', 47, 'Validar telefono_persona correcto en ADD', 'valid', 'ADD', true, 'telefono_persona correcto'],
	['persona', 'telefono_persona', 'input', 48, 'Validar format de telefono_persona en EDIT', 'format', 'EDIT', 'telefono_persona_format_KO', 'El campo telefono_persona debe ser un telefono valido de Espana'],
	['persona', 'telefono_persona', 'input', 49, 'Validar telefono_persona correcto en EDIT', 'valid', 'EDIT', true, 'telefono_persona correcto'],
	['persona', 'telefono_persona', 'input', 50, 'Validar format de telefono_persona en SEARCH', 'format', 'SEARCH', 'telefono_persona_format_KO', 'El campo telefono_persona debe ser un telefono valido de Espana'],
	['persona', 'telefono_persona', 'input', 51, 'Validar telefono_persona correcto en SEARCH', 'valid', 'SEARCH', true, 'telefono_persona correcto'],
	['persona', 'email_persona', 'input', 52, 'Validar format de email_persona en ADD', 'format', 'ADD', 'email_persona_format_KO', 'El campo email_persona debe tener un formato de email valido'],
	['persona', 'email_persona', 'input', 53, 'Validar email_persona correcto en ADD', 'valid', 'ADD', true, 'email_persona correcto'],
	['persona', 'email_persona', 'input', 54, 'Validar format de email_persona en EDIT', 'format', 'EDIT', 'email_persona_format_KO', 'El campo email_persona debe tener un formato de email valido'],
	['persona', 'email_persona', 'input', 55, 'Validar email_persona correcto en EDIT', 'valid', 'EDIT', true, 'email_persona correcto'],
	['persona', 'email_persona', 'input', 56, 'Validar format de email_persona en SEARCH', 'format', 'SEARCH', 'email_persona_format_KO', 'El campo email_persona debe tener un formato de email valido'],
	['persona', 'email_persona', 'input', 57, 'Validar email_persona correcto en SEARCH', 'valid', 'SEARCH', true, 'email_persona correcto'],
	['persona', 'foto_persona', 'file', 58, 'Validar format de foto_persona en ADD', 'personalized', 'ADD', 'foto_persona_format_KO', 'El campo foto_persona debe ser un fichero jpg o jpeg, con nombre valido y hasta 2 MB'],
	['persona', 'foto_persona', 'file', 59, 'Validar foto_persona correcta en ADD', 'valid', 'ADD', true, 'foto_persona correcta'],
	['persona', 'foto_persona', 'file', 60, 'Validar format de foto_persona en EDIT', 'personalized', 'EDIT', 'foto_persona_format_KO', 'El campo foto_persona debe ser un fichero jpg o jpeg, con nombre valido y hasta 2 MB'],
	['persona', 'foto_persona', 'file', 61, 'Validar foto_persona correcta en EDIT', 'valid', 'EDIT', true, 'foto_persona correcta'],
	['persona', 'foto_persona', 'file', 62, 'Validar format de foto_persona en SEARCH', 'personalized', 'SEARCH', 'foto_persona_format_KO', 'El campo foto_persona debe ser un fichero jpg o jpeg, con nombre valido y hasta 2 MB'],
	['persona', 'foto_persona', 'file', 63, 'Validar foto_persona correcta en SEARCH', 'valid', 'SEARCH', true, 'foto_persona correcta']
];

var persona_pruebas = [
	['persona', 'dni', 1, 1, 'ADD', {'dni': '12345678A'}, 'dni_format_KO'],
	['persona', 'dni', 2, 2, 'ADD', {'dni': '12345678Z'}, true],
	['persona', 'dni', 3, 3, 'EDIT', {'dni': '12345678A'}, 'dni_format_KO'],
	['persona', 'dni', 4, 4, 'EDIT', {'dni': '12345678Z'}, true],
	['persona', 'dni', 5, 5, 'SEARCH', {'dni': '12345678A'}, 'dni_format_KO'],
	['persona', 'dni', 6, 6, 'SEARCH', {'dni': '12345678Z'}, true],
	['persona', 'nombre_persona', 7, 7, 'ADD', {'nombre_persona': 'A'}, 'nombre_persona_min_size_KO'],
	['persona', 'nombre_persona', 8, 8, 'ADD', {'nombre_persona': 'a'.repeat(46)}, 'nombre_persona_max_size_KO'],
	['persona', 'nombre_persona', 9, 9, 'ADD', {'nombre_persona': 'Ana123'}, 'nombre_persona_format_KO'],
	['persona', 'nombre_persona', 10, 10, 'ADD', {'nombre_persona': 'Maria Jos\u00e9'}, true],
	['persona', 'nombre_persona', 11, 11, 'EDIT', {'nombre_persona': 'A'}, 'nombre_persona_min_size_KO'],
	['persona', 'nombre_persona', 12, 12, 'EDIT', {'nombre_persona': 'a'.repeat(46)}, 'nombre_persona_max_size_KO'],
	['persona', 'nombre_persona', 13, 13, 'EDIT', {'nombre_persona': 'Ana123'}, 'nombre_persona_format_KO'],
	['persona', 'nombre_persona', 14, 14, 'EDIT', {'nombre_persona': 'Maria Jos\u00e9'}, true],
	['persona', 'nombre_persona', 15, 15, 'SEARCH', {'nombre_persona': 'a'.repeat(46)}, 'nombre_persona_max_size_KO'],
	['persona', 'nombre_persona', 16, 16, 'SEARCH', {'nombre_persona': 'Ana123'}, 'nombre_persona_format_KO'],
	['persona', 'nombre_persona', 17, 17, 'SEARCH', {'nombre_persona': 'Maria Jos\u00e9'}, true],
	['persona', 'apellidos_persona', 18, 18, 'ADD', {'apellidos_persona': 'Lo'}, 'apellidos_persona_min_size_KO'],
	['persona', 'apellidos_persona', 19, 19, 'ADD', {'apellidos_persona': 'a'.repeat(101)}, 'apellidos_persona_max_size_KO'],
	['persona', 'apellidos_persona', 20, 20, 'ADD', {'apellidos_persona': 'Perez123'}, 'apellidos_persona_format_KO'],
	['persona', 'apellidos_persona', 21, 21, 'ADD', {'apellidos_persona': 'Garc\u00eda-L\u00f3pez'}, true],
	['persona', 'apellidos_persona', 22, 22, 'EDIT', {'apellidos_persona': 'Lo'}, 'apellidos_persona_min_size_KO'],
	['persona', 'apellidos_persona', 23, 23, 'EDIT', {'apellidos_persona': 'a'.repeat(101)}, 'apellidos_persona_max_size_KO'],
	['persona', 'apellidos_persona', 24, 24, 'EDIT', {'apellidos_persona': 'Perez123'}, 'apellidos_persona_format_KO'],
	['persona', 'apellidos_persona', 25, 25, 'EDIT', {'apellidos_persona': 'Garc\u00eda-L\u00f3pez'}, true],
	['persona', 'apellidos_persona', 26, 26, 'SEARCH', {'apellidos_persona': 'a'.repeat(101)}, 'apellidos_persona_max_size_KO'],
	['persona', 'apellidos_persona', 27, 27, 'SEARCH', {'apellidos_persona': 'Perez123'}, 'apellidos_persona_format_KO'],
	['persona', 'apellidos_persona', 28, 28, 'SEARCH', {'apellidos_persona': 'Garc\u00eda-L\u00f3pez'}, true],
	['persona', 'fechaNacimiento_persona', 29, 29, 'ADD', {'fechaNacimiento_persona': '31/02/2020'}, 'fechaNacimiento_persona_format_KO'],
	['persona', 'fechaNacimiento_persona', 30, 30, 'ADD', {'fechaNacimiento_persona': '23/09/2020'}, true],
	['persona', 'fechaNacimiento_persona', 31, 31, 'EDIT', {'fechaNacimiento_persona': '31/02/2020'}, 'fechaNacimiento_persona_format_KO'],
	['persona', 'fechaNacimiento_persona', 32, 32, 'EDIT', {'fechaNacimiento_persona': '23/09/2020'}, true],
	['persona', 'fechaNacimiento_persona', 33, 33, 'SEARCH', {'fechaNacimiento_persona': '31/02/2020'}, 'fechaNacimiento_persona_format_KO'],
	['persona', 'fechaNacimiento_persona', 34, 34, 'SEARCH', {'fechaNacimiento_persona': '23/09/2020'}, true],
	['persona', 'direccion_persona', 35, 35, 'ADD', {'direccion_persona': 'Calle 1'}, 'direccion_persona_min_size_KO'],
	['persona', 'direccion_persona', 36, 36, 'ADD', {'direccion_persona': 'a'.repeat(201)}, 'direccion_persona_max_size_KO'],
	['persona', 'direccion_persona', 37, 37, 'ADD', {'direccion_persona': 'Calle @@@'}, 'direccion_persona_format_KO'],
	['persona', 'direccion_persona', 38, 38, 'ADD', {'direccion_persona': 'Calle 10; 2/A'}, true],
	['persona', 'direccion_persona', 39, 39, 'EDIT', {'direccion_persona': 'Calle 1'}, 'direccion_persona_min_size_KO'],
	['persona', 'direccion_persona', 40, 40, 'EDIT', {'direccion_persona': 'a'.repeat(201)}, 'direccion_persona_max_size_KO'],
	['persona', 'direccion_persona', 41, 41, 'EDIT', {'direccion_persona': 'Calle @@@'}, 'direccion_persona_format_KO'],
	['persona', 'direccion_persona', 42, 42, 'EDIT', {'direccion_persona': 'Calle 10; 2/A'}, true],
	['persona', 'direccion_persona', 43, 43, 'SEARCH', {'direccion_persona': 'a'.repeat(201)}, 'direccion_persona_max_size_KO'],
	['persona', 'direccion_persona', 44, 44, 'SEARCH', {'direccion_persona': 'Calle @@@'}, 'direccion_persona_format_KO'],
	['persona', 'direccion_persona', 45, 45, 'SEARCH', {'direccion_persona': 'Calle 10; 2/A'}, true],
	['persona', 'telefono_persona', 46, 46, 'ADD', {'telefono_persona': '12345678'}, 'telefono_persona_format_KO'],
	['persona', 'telefono_persona', 47, 47, 'ADD', {'telefono_persona': '612345678'}, true],
	['persona', 'telefono_persona', 48, 48, 'EDIT', {'telefono_persona': '12345678'}, 'telefono_persona_format_KO'],
	['persona', 'telefono_persona', 49, 49, 'EDIT', {'telefono_persona': '612345678'}, true],
	['persona', 'telefono_persona', 50, 50, 'SEARCH', {'telefono_persona': '12345678'}, 'telefono_persona_format_KO'],
	['persona', 'telefono_persona', 51, 51, 'SEARCH', {'telefono_persona': '612345678'}, true],
	['persona', 'email_persona', 52, 52, 'ADD', {'email_persona': 'correo'}, 'email_persona_format_KO'],
	['persona', 'email_persona', 53, 53, 'ADD', {'email_persona': 'persona@example.com'}, true],
	['persona', 'email_persona', 54, 54, 'EDIT', {'email_persona': 'correo'}, 'email_persona_format_KO'],
	['persona', 'email_persona', 55, 55, 'EDIT', {'email_persona': 'persona@example.com'}, true],
	['persona', 'email_persona', 56, 56, 'SEARCH', {'email_persona': 'correo'}, 'email_persona_format_KO'],
	['persona', 'email_persona', 57, 57, 'SEARCH', {'email_persona': 'persona@example.com'}, true],
	['persona', 'foto_persona', 58, 58, 'ADD', {'foto_persona': 'foto.txt'}, 'foto_persona_format_KO'],
	['persona', 'foto_persona', 59, 59, 'ADD', {'foto_persona': 'foto.jpg'}, true],
	['persona', 'foto_persona', 60, 60, 'EDIT', {'foto_persona': 'foto.txt'}, 'foto_persona_format_KO'],
	['persona', 'foto_persona', 61, 61, 'EDIT', {'foto_persona': 'foto.jpeg'}, true],
	['persona', 'foto_persona', 62, 62, 'SEARCH', {'foto_persona': 'foto.txt'}, 'foto_persona_format_KO'],
	['persona', 'foto_persona', 63, 63, 'SEARCH', {'foto_persona': 'foto.jpg'}, true]
];

