var rolaccionfuncionalidad_def_tests = [
    ['rolaccionfuncionalidad', 'id_rol', 'input', 1, 'Validar min_size de id_rol en  ADD', 'min_size', 'ADD', 'id_rol_min_size_KO', 'El campo id_rol debe tener al menos 1 caracter'],
    ['rolaccionfuncionalidad', 'id_rol', 'input', 2, 'Validar max_size de id_rol en  ADD', 'max_size', 'ADD', 'id_rol_max_size_KO', 'El campo id_rol debe tener como máximo 11 caracteres'],
    ['rolaccionfuncionalidad', 'id_rol', 'input', 3, 'Validar format de id_rol en  ADD', 'format', 'ADD', 'id_rol_format_KO', 'El campo id_rol debe ser un número entero'],
    ['rolaccionfuncionalidad', 'id_rol', 'input', 4, 'Validar id_rol correcto en ADD', 'valid', 'ADD', true, 'id_rol correcto'],
    ['rolaccionfuncionalidad', 'id_rol', 'input', 5, 'Validar min_size de id_rol en  EDIT', 'min_size', 'EDIT', 'id_rol_min_size_KO', 'El campo id_rol debe tener al menos 1 caracter'],
    ['rolaccionfuncionalidad', 'id_rol', 'input', 6, 'Validar max_size de id_rol en  EDIT', 'max_size', 'EDIT', 'id_rol_max_size_KO', 'El campo id_rol debe tener como máximo 11 caracteres'],
    ['rolaccionfuncionalidad', 'id_rol', 'input', 7, 'Validar format de id_rol en  EDIT', 'format', 'EDIT', 'id_rol_format_KO', 'El campo id_rol debe ser un número entero'],
    ['rolaccionfuncionalidad', 'id_rol', 'input', 8, 'Validar id_rol correcto en EDIT', 'valid', 'EDIT', true, 'id_rol correcto'],
    ['rolaccionfuncionalidad', 'id_rol', 'input', 9, 'Validar max_size de id_rol en  SEARCH', 'max_size', 'SEARCH', 'id_rol_max_size_KO', 'El campo id_rol tiene como máximo 11 caracteres'],
    ['rolaccionfuncionalidad', 'id_rol', 'input', 10, 'Validar format de id_rol en  SEARCH', 'format', 'SEARCH', 'id_rol_format_KO', 'El campo id_rol debe ser un número entero'],
    ['rolaccionfuncionalidad', 'id_rol', 'input', 11, 'Validar id_rol correcto en SEARCH', 'valid', 'SEARCH', true, 'id_rol correcto'],
    ['rolaccionfuncionalidad', 'id_accion', 'input', 12, 'Validar min_size de id_accion en  ADD', 'min_size', 'ADD', 'id_accion_min_size_KO', 'El campo id_accion debe tener al menos 1 caracter'],
    ['rolaccionfuncionalidad', 'id_accion', 'input', 13, 'Validar max_size de id_accion en  ADD', 'max_size', 'ADD', 'id_accion_max_size_KO', 'El campo id_accion debe tener como máximo 11 caracteres'],
    ['rolaccionfuncionalidad', 'id_accion', 'input', 14, 'Validar format de id_accion en  ADD', 'format', 'ADD', 'id_accion_format_KO', 'El campo id_accion debe ser un número entero'],
    ['rolaccionfuncionalidad', 'id_accion', 'input', 15, 'Validar id_accion correcto en ADD', 'valid', 'ADD', true, 'id_accion correcto'],
    ['rolaccionfuncionalidad', 'id_accion', 'input', 16, 'Validar min_size de id_accion en  EDIT', 'min_size', 'EDIT', 'id_accion_min_size_KO', 'El campo id_accion debe tener al menos 1 caracter'],
    ['rolaccionfuncionalidad', 'id_accion', 'input', 17, 'Validar max_size de id_accion en  EDIT', 'max_size', 'EDIT', 'id_accion_max_size_KO', 'El campo id_accion debe tener como máximo 11 caracteres'],
    ['rolaccionfuncionalidad', 'id_accion', 'input', 18, 'Validar format de id_accion en  EDIT', 'format', 'EDIT', 'id_accion_format_KO', 'El campo id_accion debe ser un número entero'],
    ['rolaccionfuncionalidad', 'id_accion', 'input', 19, 'Validar id_accion correcto en EDIT', 'valid', 'EDIT', true, 'id_accion correcto'],
    ['rolaccionfuncionalidad', 'id_accion', 'input', 20, 'Validar max_size de id_accion en  SEARCH', 'max_size', 'SEARCH', 'id_accion_max_size_KO', 'El campo id_accion tiene como máximo 11 caracteres'],
    ['rolaccionfuncionalidad', 'id_accion', 'input', 21, 'Validar format de id_accion en  SEARCH', 'format', 'SEARCH', 'id_accion_format_KO', 'El campo id_accion debe ser un número entero'],
    ['rolaccionfuncionalidad', 'id_accion', 'input', 22, 'Validar id_accion correcto en SEARCH', 'valid', 'SEARCH', true, 'id_accion correcto'],
    ['rolaccionfuncionalidad', 'id_funcionalidad', 'input', 23, 'Validar min_size de id_funcionalidad en  ADD', 'min_size', 'ADD', 'id_funcionalidad_min_size_KO', 'El campo id_funcionalidad debe tener al menos 1 caracter'],
    ['rolaccionfuncionalidad', 'id_funcionalidad', 'input', 24, 'Validar max_size de id_funcionalidad en  ADD', 'max_size', 'ADD', 'id_funcionalidad_max_size_KO', 'El campo id_funcionalidad debe tener como máximo 11 caracteres'],
    ['rolaccionfuncionalidad', 'id_funcionalidad', 'input', 25, 'Validar format de id_funcionalidad en  ADD', 'format', 'ADD', 'id_funcionalidad_format_KO', 'El campo id_funcionalidad debe ser un número entero'],
    ['rolaccionfuncionalidad', 'id_funcionalidad', 'input', 26, 'Validar id_funcionalidad correcto en ADD', 'valid', 'ADD', true, 'id_funcionalidad correcto'],
    ['rolaccionfuncionalidad', 'id_funcionalidad', 'input', 27, 'Validar min_size de id_funcionalidad en  EDIT', 'min_size', 'EDIT', 'id_funcionalidad_min_size_KO', 'El campo id_funcionalidad debe tener al menos 1 caracter'],
    ['rolaccionfuncionalidad', 'id_funcionalidad', 'input', 28, 'Validar max_size de id_funcionalidad en  EDIT', 'max_size', 'EDIT', 'id_funcionalidad_max_size_KO', 'El campo id_funcionalidad debe tener como máximo 11 caracteres'],
    ['rolaccionfuncionalidad', 'id_funcionalidad', 'input', 29, 'Validar format de id_funcionalidad en  EDIT', 'format', 'EDIT', 'id_funcionalidad_format_KO', 'El campo id_funcionalidad debe ser un número entero'],
    ['rolaccionfuncionalidad', 'id_funcionalidad', 'input', 30, 'Validar id_funcionalidad correcto en EDIT', 'valid', 'EDIT', true, 'id_funcionalidad correcto'],
    ['rolaccionfuncionalidad', 'id_funcionalidad', 'input', 31, 'Validar max_size de id_funcionalidad en  SEARCH', 'max_size', 'SEARCH', 'id_funcionalidad_max_size_KO', 'El campo id_funcionalidad tiene como máximo 11 caracteres'],
    ['rolaccionfuncionalidad', 'id_funcionalidad', 'input', 32, 'Validar format de id_funcionalidad en  SEARCH', 'format', 'SEARCH', 'id_funcionalidad_format_KO', 'El campo id_funcionalidad debe ser un número entero'],
    ['rolaccionfuncionalidad', 'id_funcionalidad', 'input', 33, 'Validar id_funcionalidad correcto en SEARCH', 'valid', 'SEARCH', true, 'id_funcionalidad correcto']
];

var rolaccionfuncionalidad_pruebas = [
    ['rolaccionfuncionalidad', 'id_rol', 1, 1, 'ADD', {'id_rol': ''}, 'id_rol_min_size_KO'],
    ['rolaccionfuncionalidad', 'id_rol', 2, 2, 'ADD', {'id_rol': '123456789012'}, 'id_rol_max_size_KO'],
    ['rolaccionfuncionalidad', 'id_rol', 3, 3, 'ADD', {'id_rol': 'abc'}, 'id_rol_format_KO'],
    ['rolaccionfuncionalidad', 'id_rol', 3, 4, 'ADD', {'id_rol': '12,3'}, 'id_rol_format_KO'],
    ['rolaccionfuncionalidad', 'id_rol', 3, 5, 'ADD', {'id_rol': '123@'}, 'id_rol_format_KO'],
    ['rolaccionfuncionalidad', 'id_rol', 4, 6, 'ADD', {'id_rol': '123'}, true],
    ['rolaccionfuncionalidad', 'id_rol', 5, 7, 'EDIT', {'id_rol': ''}, 'id_rol_min_size_KO'],
    ['rolaccionfuncionalidad', 'id_rol', 6, 8, 'EDIT', {'id_rol': '123456789012'}, 'id_rol_max_size_KO'],
    ['rolaccionfuncionalidad', 'id_rol', 7, 9, 'EDIT', {'id_rol': 'abc'}, 'id_rol_format_KO'],
    ['rolaccionfuncionalidad', 'id_rol', 7, 10, 'EDIT', {'id_rol': '12,3'}, 'id_rol_format_KO'],
    ['rolaccionfuncionalidad', 'id_rol', 7, 11, 'EDIT', {'id_rol': '123@'}, 'id_rol_format_KO'],
    ['rolaccionfuncionalidad', 'id_rol', 8, 12, 'EDIT', {'id_rol': '123'}, true],
    ['rolaccionfuncionalidad', 'id_rol', 9, 13, 'SEARCH', {'id_rol': '123456789012'}, 'id_rol_max_size_KO'],
    ['rolaccionfuncionalidad', 'id_rol', 10, 14, 'SEARCH', {'id_rol': 'abc'}, 'id_rol_format_KO'],
    ['rolaccionfuncionalidad', 'id_rol', 10, 15, 'SEARCH', {'id_rol': '12,3'}, 'id_rol_format_KO'],
    ['rolaccionfuncionalidad', 'id_rol', 10, 16, 'SEARCH', {'id_rol': '123@'}, 'id_rol_format_KO'],
    ['rolaccionfuncionalidad', 'id_rol', 11, 17, 'SEARCH', {'id_rol': '123'}, true],
    ['rolaccionfuncionalidad', 'id_accion', 12, 18, 'ADD', {'id_accion': ''}, 'id_accion_min_size_KO'],
    ['rolaccionfuncionalidad', 'id_accion', 13, 19, 'ADD', {'id_accion': '123456789012'}, 'id_accion_max_size_KO'],
    ['rolaccionfuncionalidad', 'id_accion', 14, 20, 'ADD', {'id_accion': 'abc'}, 'id_accion_format_KO'],
    ['rolaccionfuncionalidad', 'id_accion', 14, 21, 'ADD', {'id_accion': '12,3'}, 'id_accion_format_KO'],
    ['rolaccionfuncionalidad', 'id_accion', 14, 22, 'ADD', {'id_accion': '123@'}, 'id_accion_format_KO'],
    ['rolaccionfuncionalidad', 'id_accion', 15, 23, 'ADD', {'id_accion': '123'}, true],
    ['rolaccionfuncionalidad', 'id_accion', 16, 24, 'EDIT', {'id_accion': ''}, 'id_accion_min_size_KO'],
    ['rolaccionfuncionalidad', 'id_accion', 17, 25, 'EDIT', {'id_accion': '123456789012'}, 'id_accion_max_size_KO'],
    ['rolaccionfuncionalidad', 'id_accion', 18, 26, 'EDIT', {'id_accion': 'abc'}, 'id_accion_format_KO'],
    ['rolaccionfuncionalidad', 'id_accion', 18, 27, 'EDIT', {'id_accion': '12,3'}, 'id_accion_format_KO'],
    ['rolaccionfuncionalidad', 'id_accion', 18, 28, 'EDIT', {'id_accion': '123@'}, 'id_accion_format_KO'],
    ['rolaccionfuncionalidad', 'id_accion', 19, 29, 'EDIT', {'id_accion': '123'}, true],
    ['rolaccionfuncionalidad', 'id_accion', 20, 30, 'SEARCH', {'id_accion': '123456789012'}, 'id_accion_max_size_KO'],
    ['rolaccionfuncionalidad', 'id_accion', 21, 31, 'SEARCH', {'id_accion': 'abc'}, 'id_accion_format_KO'],
    ['rolaccionfuncionalidad', 'id_accion', 21, 32, 'SEARCH', {'id_accion': '12,3'}, 'id_accion_format_KO'],
    ['rolaccionfuncionalidad', 'id_accion', 21, 33, 'SEARCH', {'id_accion': '123@'}, 'id_accion_format_KO'],
    ['rolaccionfuncionalidad', 'id_accion', 22, 34, 'SEARCH', {'id_accion': '123'}, true],
    ['rolaccionfuncionalidad', 'id_funcionalidad', 23, 35, 'ADD', {'id_funcionalidad': ''}, 'id_funcionalidad_min_size_KO'],
    ['rolaccionfuncionalidad', 'id_funcionalidad', 24, 36, 'ADD', {'id_funcionalidad': '123456789012'}, 'id_funcionalidad_max_size_KO'],
    ['rolaccionfuncionalidad', 'id_funcionalidad', 25, 37, 'ADD', {'id_funcionalidad': 'abc'}, 'id_funcionalidad_format_KO'],
    ['rolaccionfuncionalidad', 'id_funcionalidad', 25, 38, 'ADD', {'id_funcionalidad': '12,3'}, 'id_funcionalidad_format_KO'],
    ['rolaccionfuncionalidad', 'id_funcionalidad', 25, 39, 'ADD', {'id_funcionalidad': '123@'}, 'id_funcionalidad_format_KO'],
    ['rolaccionfuncionalidad', 'id_funcionalidad', 26, 40, 'ADD', {'id_funcionalidad': '123'}, true],
    ['rolaccionfuncionalidad', 'id_funcionalidad', 27, 41, 'EDIT', {'id_funcionalidad': ''}, 'id_funcionalidad_min_size_KO'],
    ['rolaccionfuncionalidad', 'id_funcionalidad', 28, 42, 'EDIT', {'id_funcionalidad': '123456789012'}, 'id_funcionalidad_max_size_KO'],
    ['rolaccionfuncionalidad', 'id_funcionalidad', 29, 43, 'EDIT', {'id_funcionalidad': 'abc'}, 'id_funcionalidad_format_KO'],
    ['rolaccionfuncionalidad', 'id_funcionalidad', 29, 44, 'EDIT', {'id_funcionalidad': '12,3'}, 'id_funcionalidad_format_KO'],
    ['rolaccionfuncionalidad', 'id_funcionalidad', 29, 45, 'EDIT', {'id_funcionalidad': '123@'}, 'id_funcionalidad_format_KO'],
    ['rolaccionfuncionalidad', 'id_funcionalidad', 30, 46, 'EDIT', {'id_funcionalidad': '123'}, true],
    ['rolaccionfuncionalidad', 'id_funcionalidad', 31, 47, 'SEARCH', {'id_funcionalidad': '123456789012'}, 'id_funcionalidad_max_size_KO'],
    ['rolaccionfuncionalidad', 'id_funcionalidad', 32, 48, 'SEARCH', {'id_funcionalidad': 'abc'}, 'id_funcionalidad_format_KO'],
    ['rolaccionfuncionalidad', 'id_funcionalidad', 32, 49, 'SEARCH', {'id_funcionalidad': '12,3'}, 'id_funcionalidad_format_KO'],
    ['rolaccionfuncionalidad', 'id_funcionalidad', 32, 50, 'SEARCH', {'id_funcionalidad': '123@'}, 'id_funcionalidad_format_KO'],
    ['rolaccionfuncionalidad', 'id_funcionalidad', 33, 51, 'SEARCH', {'id_funcionalidad': '123'}, true]
];
